### ISSUE TITLE
Changer les clefs de traductions

### ISSUE THREAD

**Issue by vouiv-re** [uurshin/minotaure#5]
* En anglais
* Séparer les mots pas un underscore
* Technique
* Description minimale
* Composer la clef en composant par un thème si c'est possible
* Mettre les clefs au singulier
* Pas de majuscule

**Comment by uurshin** [comment]
@vouiv-re Il faudrait aussi utiliser i18n de manière globale pour épurer un peu le code : 

- [ ] Passer tous les appels à t() en $t() dans les parties template des components
- [ ] Enlever l'import de i18n en haut des components
- [ ] Enlever la déclaration de t dans les parties setup() et/ou data() des components
- [ ] Charger chaque page pour vérifier que ça ne produit pas d'erreur
